/**
 * Dictionnaire français des capacités Pokémon (Générations 1 à 4).
 */
export const FRENCH_MOVE_NAMES: Record<string, string> = {
  tackle: "Charge", scratch: "Griffe", pound: "Écras'Face",
  growl: "Rugissement", leer: "Groz'Yeux", tailwhip: "Mimi-Queue",
  ember: "Flammèche", watergun: "Pistolet à O", absorb: "Vol-Vie",
  vinewhip: "Fouet Lianes", spark: "Étincelle", quickattack: "Vive-Attaque",
  bite: "Morsure", headbutt: "Coup d'Boule", confusion: "Choc Mental",
  poisonsting: "Dard-Venin", peck: "Picpic", gust: "Tornade",
  sandattack: "Jet de Sable", stringshot: "Sécrétion", bubble: "Écume",
  withdraw: "Repli", harden: "Armure", defensecurl: "Boul'Armure",
  supersonic: "Ultrason", astonish: "Étonnement", smog: "Purédpois",
  lick: "Léchouille", hypnosis: "Hypnose", screech: "Grincement",
  sing: "Berceuse", charm: "Charme", thundershock: "Éclair",
  thunderwave: "Cage-Éclair", wrap: "Ligotage", splash: "Trempette",
  teleport: "Téléport", sketch: "Gribouille", present: "Cadeau",
  rockthrow: "Jet-Pierres", mudslap: "Coud'Boue", mudshot: "Tir de Boue",
  furyattack: "Furie", furyswipes: "Combo-Griffe", karatechop: "Poing-Karaté",
  machpunch: "Mach Punch", forcepalm: "Forte-Paume", closecombat: "Close Combat",
  endure: "Ténacité", feintattack: "Feinte", payback: "Représailles",
  snarl: "Aboiement", fakeout: "Bluff", faketears: "Croco Larme",
  rest: "Repos", snore: "Ronflement", sleeptalk: "Blabla Dodo",
  nightshade: "Ombre Nocturne", shadowsneak: "Ombre Portée", shadowclaw: "Griffe Ombre",
  shadowball: "Ball'Ombre", icywind: "Vent Glace", powdersnow: "Poudreuse",
  iceshard: "Éclats Glace", icebeam: "Laser Glace", blizzard: "Blizzard",
  rocksmash: "Éclate-Roc", stealthrock: "Piège de Roc", rollout: "Roulade",
  gyroball: "Gyroballe", irondefense: "Mur de Fer", metalclaw: "Griffe Acier",
  ironhead: "Tête de Fer", flashcannon: "Luminocanon", bulletpunch: "Pisto-Poing",
  dragonrage: "Draco-Rage", dragonbreath: "Dracosouffle", dragonpulse: "Dracochoc",
  dragonclaw: "Dracogriffe", roost: "Atterrissage", aircutter: "Tranch'Air",
  airslash: "Lame d'Air", bravebird: "Rapace", wingattack: "Cru-Ailes",
  aerialace: "Aéropique", drillpeck: "Bec Vrille", fly: "Vol",
  ancientpower: "Pouvoir Antique", bugbuzz: "Bourdon", signalbeam: "Rayon Signal",
  xscissor: "Plaie-Croix", megahorn: "Mégacorne", razorleaf: "Tranch'Herbe",
  magicalleaf: "Feuille Magik", energyball: "Éco-Sphère", gigadrain: "Giga-Sangsue",
  megadrain: "Méga-Sangsue", solarbeam: "Lance-Soleil", woodhammer: "Martobois",
  seedbomb: "Canon Graine", leafblade: "Lame Feuille", leafstorm: "Tempête Verte",
  grassknot: "Nœud Herbe", petaldance: "Danse-Fleur", stunspore: "Para-Spore",
  poisonpowder: "Poudre Toxik", sleeppowder: "Poudre Dodo", spore: "Spore",
  synthesis: "Synthèse", protect: "Abri", swordsdance: "Danse-Lames",
  dragondance: "Danse Draco", agility: "Hâte", calmmind: "Plénitude",
  nastyplot: "Machination", toxic: "Toxik", sludge: "Détritus",
  sludgebomb: "Bomb-Beurk", crosschop: "Coup-Croix", earthquake: "Séisme",
  earthpower: "Telluriforce", flamethrower: "Lance-Flammes", fireblast: "Déflagration",
  firepunch: "Poing Feu", thunderpunch: "Poing Éclair", icepunch: "Poing Glace",
  thunderbolt: "Tonnerre", thunder: "Fatal-Foudre", discharge: "Coup d'Jus",
  surf: "Surf", hydropump: "Hydrocanon", waterfall: "Cascade",
  psychic: "Psyko", psyshock: "Choc Psy", zenheadbutt: "Psykoud'Boul",
  aurasphere: "Aurasphère", focusblast: "Exploforce", darkpulse: "Vibrobscur",
  crunch: "Mâchouille", nightslash: "Tranche-Nuit", stoneedge: "Lame de Roc",
  rockslide: "Éboulement", sacredfire: "Feu Sacré", roaroftime: "Hurle-Temps",
  spacialrend: "Spatio-Rift", shadowforce: "Revenant", judgment: "Jugement",
  hyperfang: "Croc de Mort", superfang: "Croc Fatal", doubleedge: "Damoclès",
  takedown: "Bélier", bodyslam: "Plaquage", slash: "Tranche",
  triattack: "Triplattaque", hyperbeam: "Ultralaser", gigaimpact: "Giga Impact",
  acidspray: "Bombe Acide", poisonjab: "Direct Toxik", gunkshot: "Détricanon",
  crosspoison: "Poison-Croix", mudbomb: "Boue-Bombe", drillrun: "Tunnelier", dig: "Tunnel",
  rocktomb: "Tomberoche", powergem: "Rayon Gemme",
  icefang: "Crocs Givre", firefang: "Crocs Feu", thunderfang: "Crocs Éclair",
  flamecharge: "Nitrocharge", flareblitz: "Boutefeu", lavaplume: "Ébullilave",
  aquajet: "Aqua-Jet", aquatail: "Hydroqueue", muddywater: "Ocroupi",
  scald: "Ébullition", bubblebeam: "Bulles d'O",
  chargebeam: "Rayon Chargé", voltswitch: "Change Éclair",
  bulletseed: "Balle Graine", drainingkiss: "Vampibaiser", shadowpunch: "Poing Ombre",
  dreameater: "Dévorêve", psybeam: "Rafale Psy", extrasensory: "Extrasenseur",
  focuspunch: "Mitra-Poing", dynamicpunch: "Dynamopoing", submission: "Sacrifice",
  lowkick: "Balayage", brickbreak: "Casse-Brique", hammerarm: "Marto-Poing",
  dragonrush: "Dracocharge", outrage: "Colère",
  assurance: "Assurance", suckerpunch: "Coup Bas",
  magnetrise: "Vol Magnétique",
  sweetscent: "Doux Parfum",
  taunt: "Provoc", torment: "Tourmente", disable: "Entrave",
  spikes: "Picots", toxicspikes: "Pics Toxik", destinybond: "Lien du Destin",
  perishsong: "Requiem", batonpass: "Relais", bellydrum: "Cognobidon",
  mirrorcoat: "Voile Miroir", counter: "Riposte", reflect: "Protection",
  lightscreen: "Mur Lumière", barrier: "Bouclier", amnesia: "Amnésie",
  cosmicpower: "Puissance Cosmique", acidarmor: "Acidarmure", recover: "Soin",
  softboiled: "E-Coque", milkdrink: "Lait à Boire", slackoff: "Paresse",
  wish: "Vœu", healbell: "Glas de Soin",
  aromatherapy: "Aromathérapie", transform: "Morphing", metronome: "Métronome",
};

export function getMoveFrenchName(id: string, fallbackName?: string): string {
  return FRENCH_MOVE_NAMES[id.toLowerCase()] || fallbackName || id;
}
