export const FRENCH_SPECIES_NAMES: Record<string, string> = {
  bulbasaur: "Bulbizarre", ivysaur: "Herbizarre", venusaur: "Florizarre",
  charmander: "Salamèche", charmeleon: "Reptincel", charizard: "Dracaufeu",
  squirtle: "Carapuce", wartortle: "Carabaffe", blastoise: "Tortank",
  caterpie: "Chenipan", metapod: "Chrysacier", butterfree: "Papilusion",
  weedle: "Aspicot", kakuna: "Coconfort", beedrill: "Dardargnan",
  pidgey: "Roucool", pidgeotto: "Roucoups", pidgeot: "Roucarnage",
  rattata: "Rattata", raticate: "Rattatac",
  spearow: "Piafabec", fearow: "Rapasdepic",
  ekans: "Abo", arbok: "Arbok",
  pikachu: "Pikachu", raichu: "Raichu",
  sandshrew: "Sabelette", sandslash: "Sablaireau",
  nidoranf: "Nidoran♀", nidorina: "Nidorina", nidoqueen: "Nidoqueen",
  nidoranm: "Nidoran♂", nidorino: "Nidorino", nidoking: "Nidoking",
  clefairy: "Mélofée", clefable: "Mélodelfe",
  vulpix: "Goupix", ninetales: "Feunard",
  jigglypuff: "Rondoudou", wigglytuff: "Grodoudou",
  zubat: "Nosferapti", golbat: "Nosferalto",
  oddish: "Mystherbe", gloom: "Ortide", vileplume: "Rafflesia",
  paras: "Paras", parasect: "Parasect",
  venonat: "Mimitoss", venomoth: "Aéromite",
  diglett: "Taupiqueur", dugtrio: "Triopikeur",
  meowth: "Miaouss", persian: "Persian",
  psyduck: "Psykokwak", golduck: "Akwakwak",
  mankey: "Férosinge", primeape: "Colossinge",
  growlithe: "Caninos", arcanine: "Arcanin",
  poliwag: "Ptitard", poliwhirl: "Têtarte", poliwrath: "Tartard",
  abra: "Abra", kadabra: "Kadabra", alakazam: "Alakazam",
  machop: "Machoc", machoke: "Machopeur", machamp: "Mackogneur",
  bellsprout: "Chétiflor", weepinbell: "Boustiflor", victreebel: "Empiflor",
  tentacool: "Tentacool", tentacruel: "Tentacruel",
  geodude: "Racaillou", graveler: "Gravalanch", golem: "Grolem",
  ponyta: "Ponyta", rapidash: "Galopa",
  slowpoke: "Ramoloss", slowbro: "Flagadoss",
  magnemite: "Magnéti", magneton: "Magnéton",
  farfetchd: "Canarticho",
  doduo: "Doduo", dodrio: "Dodrio",
  seel: "Otaria", dewgong: "Lamantine",
  grimer: "Tadmorv", muk: "Grotadmorv",
  shellder: "Kokiyas", cloyster: "Crustabri",
  gastly: "Fantominus", haunter: "Spectrum", gengar: "Ectoplasma",
  onix: "Onix",
  drowzee: "Soporifik", hypno: "Hypnomade",
  krabby: "Krabby", kingler: "Krabboss",
  voltorb: "Voltorbe", electrode: "Électrode",
  exeggcute: "Noeunoeuf", exeggutor: "Noadkoko",
  cubone: "Osselait", marowak: "Ossatueur",
  hitmonlee: "Kicklee", hitmonchan: "Tygnon",
  lickitung: "Excelangue",
  koffing: "Smogo", weezing: "Smogogo",
  rhyhorn: "Rhinocorne", rhydon: "Rhinoféros",
  chansey: "Leveinard",
  tangela: "Saquedeneu",
  kangaskhan: "Kangourex",
  horsea: "Hypotrempe", seadra: "Hypocéan",
  goldeen: "Poissirène", seaking: "Poissoroy",
  staryu: "Stari", starmie: "Staross",
  mrmime: "M. Mime",
  scyther: "Insécateur",
  jynx: "Lippoutou",
  electabuzz: "Élektek",
  magmar: "Magmar",
  pinsir: "Scarabrute",
  tauros: "Tauros",
  magikarp: "Magicarpe", gyarados: "Léviator",
  lapras: "Lokhlass",
  ditto: "Métamorph",
  eevee: "Évoli", vaporeon: "Aquali", jolteon: "Voltali", flareon: "Pyroli",
  porygon: "Porygon",
  omanyte: "Amonita", omastar: "Amonistar",
  kabuto: "Kabuto", kabutops: "Kabutops",
  aerodactyl: "Ptéra",
  snorlax: "Ronflex",
  articuno: "Artikodin", zapdos: "Électhor", moltres: "Sulfura",
  dratini: "Minidraco", dragonair: "Draco", dragonite: "Dracolosse",
  mewtwo: "Mewtwo", mew: "Mew",
  // Gen 2
  chikorita: "Germignon", bayleef: "Macronium", meganium: "Méganium",
  cyndaquil: "Héricendre", quilava: "Feurisson", typhlosion: "Typhlosion",
  totodile: "Kaiminus", croconaw: "Crocrodil", feraligatr: "Aligatueur",
  sentret: "Fouinette", furret: "Fouinar",
  hoothoot: "Hoothoot", noctowl: "Noarfang",
  ledyba: "Coxy", ledian: "Coxyclaque",
  spinarak: "Mimigal", ariados: "Migalos",
  crobat: "Nostenfer",
  chinchou: "Loupio", lanturn: "Lanturn",
  pichu: "Pichu", cleffa: "Mélo", igglybuff: "Toudoudou",
  togepi: "Togepi", togetic: "Togetic",
  natu: "Natu", xatu: "Xatu",
  mareep: "Wattouat", flaaffy: "Lainergie", ampharos: "Pharamp",
  bellossom: "Joliflor", marill: "Marill", azumarill: "Azumarill",
  sudowoodo: "Simularbre", politoed: "Tarpaud",
  hoppip: "Granivol", skiploom: "Floravol", jumpluff: "Cotovol",
  aipom: "Capumain", sunkern: "Tournegrain", sunflora: "Héliatronc",
  yanma: "Yanma", wooper: "Axoloto", quagsire: "Maraiste",
  espeon: "Mentali", umbreon: "Noctali",
  murkrow: "Cornèbre", slowking: "Roigada",
  misdreavus: "Feuforêve", unown: "Zarbi",
  wobbuffet: "Qulbutoké", girafarig: "Girafarig",
  pineco: "Pomdepik", forretress: "Foretress",
  dunsparce: "Insolourdo", gligar: "Scorplane",
  steelix: "Steelix", snubbull: "Snubbull", granbull: "Granbull",
  qwilfish: "Qwilfish", scizor: "Cizayox", shuckle: "Caratroc",
  heracross: "Scarhino", sneasel: "Farfuret",
  teddiursa: "Teddiursa", ursaring: "Ursaring",
  slugma: "Limagma", magcargo: "Volcaropod",
  swinub: "Marcacrin", piloswine: "Cochignon",
  corsola: "Corayon", remoraid: "Rémoraid", octillery: "Octillery",
  delibird: "Cadoizo", mantine: "Démanta", skarmory: "Airmure",
  houndour: "Malosse", houndoom: "Démolosse",
  kingdra: "Hyporoi", phanpy: "Phanpy", donphan: "Donphan",
  porygon2: "Porygon2", stantler: "Cerfrousse", smeargle: "Queulorior",
  tyrogue: "Debugant", hitmontop: "Kapoera",
  smoochum: "Lippouti", elekid: "Élekid", magby: "Magby",
  miltank: "Écrémeuh", blissey: "Leuphorie",
  raikou: "Raikou", entei: "Entei", suicune: "Suicune",
  larvitar: "Embrylex", pupitar: "Ymphect", tyranitar: "Tyranocif",
  lugia: "Lugia", hooh: "Ho-Oh", celebi: "Celebi",
  // Gen 3
  treecko: "Arcko", grovyle: "Massko", sceptile: "Jungko",
  torchic: "Poussifeu", combusken: "Galifeu", blaziken: "Braségali",
  mudkip: "Gobou", marshtomp: "Flobio", swampert: "Laggron",
  poochyena: "Medhyèna", mightyena: "Grahyèna",
  zigzagoon: "Zigzaton", linoone: "Linéon",
  wurmple: "Chenipotte", silcoon: "Armulys", beautifly: "Charmillon",
  cascoon: "Blindalys", dustox: "Papinox",
  lotad: "Nénupiot", lombre: "Lombre", ludicolo: "Ludicolo",
  seedot: "Grainipiot", nuzleaf: "Pifeuil", shiftry: "Tengalice",
  taillow: "Nirondelle", swellow: "Hélédelle",
  wingull: "Goélise", pelipper: "Bekipan",
  ralts: "Tarsal", kirlia: "Kirlia", gardevoir: "Gardevoir",
  surskit: "Arakdo", masquerain: "Maskadra",
  shroomish: "Balignon", breloom: "Chapignon",
  slakoth: "Parecool", vigoroth: "Vigoroth", slaking: "Monaflèmit",
  nincada: "Ningale", ninjask: "Ninjask", shedinja: "Munja",
  whismur: "Chuchmur", loudred: "Ramboum", exploud: "Brouhabam",
  makuhita: "Makuhita", hariyama: "Hariyama",
  azurill: "Azurill", nosepass: "Tarinor",
  skitty: "Skitty", delcatty: "Delcatty",
  sableye: "Ténéfix", mawile: "Mysdibule",
  aron: "Galekid", lairon: "Galegon", aggron: "Galeking",
  meditite: "Méditikka", medicham: "Charmina",
  electrike: "Dynavolt", manectric: "Élecsprint",
  plusle: "Posipi", minun: "Négapi",
  volbeat: "Muciole", illumise: "Lumivole",
  roselia: "Rosélia", gulpin: "Gloupti", swalot: "Avaltout",
  carvanha: "Carvanha", sharpedo: "Sharpedo",
  wailmer: "Wailmer", wailord: "Wailord",
  numel: "Chamallot", camerupt: "Camérupt",
  torkoal: "Chartor", spoink: "Spoink", grumpig: "Groret",
  spinda: "Spinda", trapinch: "Kraknoix", vibrava: "Vibraninf", flygon: "Libégon",
  cacnea: "Cacnea", cacturne: "Cacturne",
  swablu: "Tylton", altaria: "Altaria",
  zangoose: "Mangriff", seviper: "Séviper",
  lunatone: "Séléroc", solrock: "Solaroc",
  barboach: "Barloche", whiscash: "Barbicha",
  corphish: "Écrapince", crawdaunt: "Colhomard",
  baltoy: "Balbuto", claydol: "Kaorine",
  lileep: "Lilia", cradily: "Vacillys",
  anorith: "Anorith", armaldo: "Armaldo",
  feebas: "Barpau", milotic: "Milobellus",
  castform: "Morphéo", kecleon: "Kecleon",
  shuppet: "Polichombr", banette: "Branette",
  duskull: "Skelénox", dusclops: "Téraclope",
  tropius: "Tropius", chimecho: "Éoko",
  absol: "Absol", wynaut: "Okéoké",
  snorunt: "Stalgamin", glalie: "Oniglali",
  spheal: "Obalie", sealeo: "Phogleur", walrein: "Kaimorse",
  clamperl: "Coquiperl", huntail: "Serpang", gorebyss: "Rosabyss",
  relicanth: "Relicanth", luvdisc: "Lovdisc",
  bagon: "Draby", shelgon: "Drackhaus", salamence: "Drattak",
  beldum: "Terhal", metang: "Métang", metagross: "Métalosse",
  regirock: "Regirock", regice: "Regice", registeel: "Registeel",
  latias: "Latias", latios: "Latios",
  kyogre: "Kyogre", groudon: "Groudon", rayquaza: "Rayquaza",
  jirachi: "Jirachi", deoxys: "Deoxys",
  // Gen 4
  turtwig: "Tortipouss", grotle: "Boskara", torterra: "Torterra",
  chimchar: "Ouisticram", monferno: "Chimpenfeu", infernape: "Simiabraz",
  piplup: "Tiplouf", prinplup: "Prinplouf", empoleon: "Pingoléon",
  starly: "Étourmi", staravia: "Étourvol", staraptor: "Étouraptor",
  bidoof: "Keunotor", bibarel: "Castorno",
  kricketot: "Crikzik", kricketune: "Mélokrik",
  shinx: "Lixy", luxio: "Luxio", luxray: "Luxray",
  budew: "Rozbouton", roserade: "Roserade",
  cranidos: "Kranidos", rampardos: "Charkos",
  shieldon: "Dinoclier", bastiodon: "Bastiodon",
  burmy: "Cheniti", wormadam: "Cheniselle", mothim: "Papilord",
  combee: "Apitrini", vespiquen: "Apireine",
  pachirisu: "Pachirisu", buizel: "Mustébouée", floatzel: "Mustéflott",
  cherubi: "Ceribou", cherrim: "Ceriflor",
  shellos: "Sancoki", gastrodon: "Tritosor",
  ambipom: "Capidextre", drifloon: "Baudrive", drifblim: "Grodrive",
  buneary: "Laporeille", lopunny: "Lockpin",
  mismagius: "Magirêve", honchkrow: "Corboss",
  glameow: "Chaglam", purugly: "Chaffreux",
  chingling: "Korillon", stunky: "Moufouette", skutank: "Moufflair",
  bronzor: "Archéomire", bronzong: "Archéodong",
  bonsly: "Manzaï", mimejr: "Mime Jr.",
  happiny: "Ptiravi", chatot: "Pijako",
  spiritomb: "Spiritomb", gible: "Griknot", gabite: "Carmache", garchomp: "Carchacrok",
  munchlax: "Goinfrex", riolu: "Riolu", lucario: "Lucario",
  hippopotas: "Hippopotas", hippowdon: "Hippodocus",
  skorupi: "Rapion", drapion: "Drascore",
  croagunk: "Cradopaud", toxicroak: "Coatox",
  carnivine: "Vortente", finneon: "Écayon", lumineon: "Luminéon",
  mantyke: "Babimanta", snover: "Blizzi", abomasnow: "Blizzaroi",
  weavile: "Dimoret", magnezone: "Magnézone", lickilicky: "Coudlangue",
  rhyperior: "Rhinastoc", tangrowth: "Bouldeneu", electivire: "Élekable", magmortar: "Maganon",
  togekiss: "Togekiss", yanmega: "Yanméga", leafeon: "Phyllali", glaceon: "Givrali",
  gliscor: "Scorvol", mamoswine: "Mammochon", porygonz: "Porygon-Z",
  gallade: "Gallame", probopass: "Tarinorme", dusknoir: "Noctunoir", froslass: "Momartik",
  rotom: "Motisma",
  uxie: "Créhelf", mesprit: "Créfollet", azelf: "Créfadet",
  dialga: "Dialga", palkia: "Palkia", heatran: "Heatran",
  regigigas: "Regigigas", giratina: "Giratina", cresselia: "Cresselia",
  phione: "Phione", manaphy: "Manaphy", darkrai: "Darkrai",
  shaymin: "Shaymin", arceus: "Arceus"
};

export function getSpeciesFrenchName(speciesId: string, fallbackName?: string): string {
  const normalized = speciesId.toLowerCase().replace(/[^a-z0-9]/g, "");
  return FRENCH_SPECIES_NAMES[normalized] || fallbackName || speciesId;
}
